### ISSUE TITLE
add support for date-range-change in diagram

### ISSUE THREAD

**Issue by dex2000** [opening-hours/opening_hours-statistics#10]
date range is now 2 Years for "what is in the database"
Should be nice to edit range to check sometimes the diagram for one year or last 2-3 monts or so.

**Comment by dex2000** [comment]
ah fck, it is there ... will go to test it ...

**Comment by ypid** [comment]
Have you tried to click at the start position, hold and move the mouse to the end position. Then release the mouse. This should zoom in. You can do the same at the second overview below to increase the shown range :)

**Comment by dex2000** [comment]
Time to go to bed or so ...
