### ISSUE TITLE
Add support for opening_hours:covid19 key

### ISSUE THREAD

**Issue by HubMiner** [opening-hours/opening_hours-statistics#19]
Please add support for opening_hours:covid19 key.  Note, additional values are valid for this key: same|*|restricted
https://wiki.openstreetmap.org/wiki/Key:opening_hours:covid19

**Comment by ypid** [comment]
Thanks for the hint, sounds good to me. Done that.

As I am using taginfo as a very inexpensive data source (https://taginfo.openstreetmap.org/taginfo/apidoc), I don’t have inexpensive access to history. I could use Overpass API for that, but it would cost quite a bit of CPU time and I am trying to save resources. Statistics for opening_hours:covid19 will be tracked starting today. Let me know if something does not work.
