### ISSUE TITLE
"server offline" hard coded?

### ISSUE THREAD

**Issue by dex2000** [opening-hours/opening_hours-statistics#8]
the stats say above the stat-image-diagram: "server offline"with link to https://github.com/ypid/opening_hours_map/issues/28

I think its wrong, or what is offline?

**Comment by ypid** [comment]
That is the correct link. Check the reference of the issue for details. The statistic is processed on this server.

**Comment by dex2000** [comment]
Uhm, the issue says http://openingh.openstreetmap.de/ is offline, but isn't. The redirect on ypid.de is wrong/offline

*confused*

**Comment by ypid** [comment]
@dex2000 https://github.com/opening-hours/opening_hours_map/issues/28 is closed meaning that the server is reachable again. ypid.de is currently under maintenance. The redirects are currently broken. I hope to fix this in a few days. Refer to this more recent issue: https://github.com/opening-hours/opening_hours_map/issues/43

Anything unclear? If yes, feel free to ask, if not, can you close :smile:
